name: Download and Convert Video to 480p

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
        type: string

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install ffmpeg, wget, and curl
      - name: Install ffmpeg, wget, and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg wget curl

      # Install Python dependencies (requests only, if needed elsewhere)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Create a directory for downloads and converted files
      - name: Create directories
        run: |
          mkdir -p downloads
          mkdir -p converted

      # Download file with curl (for header check) and wget (for download with progress bar)
      - name: Download file
        run: |
          # Extract filename from URL
          URL="${{ github.event.inputs.file_url }}"
          FILENAME=$(basename "$URL")
          OUTPUT_PATH="downloads/$FILENAME"

          # Use curl to check if the URL is accessible with retries
          echo "Checking URL accessibility with curl..."
          curl --retry 3 --retry-delay 5 --head --fail --silent "$URL"
          if [ $? -ne 0 ]; then
            echo "Error: URL is not accessible or file does not exist."
            exit 1
          fi

          # Use wget to download the file with progress bar
          echo "Downloading file with wget..."
          wget --progress=bar:force --output-document="$OUTPUT_PATH" "$URL"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to download file with wget."
            exit 1
          fi

      # Convert video files to 480p, rename, and delete originals
      - name: Convert videos to 480p
        run: |
          python -c "
          import os
          import subprocess
          import glob

          download_dir = 'downloads'
          converted_dir = 'converted'

          # Supported video extensions
          video_extensions = ['*.mp4', '*.mkv', '*.avi', '*.mov', '*.flv', '*.wmv']

          for ext in video_extensions:
              for file_path in glob.glob(f'{download_dir}/{ext}'):
                  filename = os.path.basename(file_path)
                  # Replace spaces with dots
                  new_filename = '480' + filename.replace(' ', '.')
                  output_path = os.path.join(converted_dir, new_filename)

                  # Convert video to 480p with automatic adjustments
                  cmd = [
                      'ffmpeg',
                      '-i', file_path,
                      '-vf', 'scale=-2:480',
                      '-c:v', 'libx264',
                      '-preset', 'medium',
                      '-crf', '23',
                      '-c:a', 'aac',
                      '-b:a', '128k',
                      '-y',  # Overwrite output files without asking
                      output_path
                  ]
                  subprocess.run(cmd, check=True)
                  
                  # Delete original file
                  os.remove(file_path)
          "

      # Create a release and upload converted files
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest Release
          draft: false
          prerelease: false

      # Upload converted files to the release
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: converted/*
          asset_name: '*.mp4,*.mkv,*.avi,*.mov,*.flv,*.wmv'
          asset_content_type: video/*

      # Clean up directories
      - name: Clean up
        run: |
          rm -rf downloads converted
