name: Download Workflow

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL, magnet link, torrent link, or .txt file with links'
        required: true
        type: string
      compress:
        description: 'Compress applicable files (e.g., videos to 480p, images reduced size, APK images compressed)'
        required: false
        type: boolean
        default: false
      archive:
        description: 'Archive each file individually with maximum compression (7z)'
        required: false
        type: boolean
        default: false

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y aria2 ffmpeg p7zip-full curl wget
          pip install requests beautifulsoup4 fake-useragent pillow selenium

      - name: Run download script
        run: python download.py "${{ inputs.url }}" ${{ inputs.compress }} ${{ inputs.archive }}

      - name: Create or update release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release=$(gh release view latest --json id -q .id 2>/dev/null || echo "")
          if [ -z "$release" ]; then
            gh release create latest --title "Latest Downloads" -F notes.md
          else
            gh release edit latest --title "Latest Downloads" -F notes.md
          fi
          gh release upload latest files/* --clobber
